name: 'reset --hard to commit'
description: 'Github Action to reset a given branch to a given commit'
inputs:
    github-token:
        description: 'Github Actions Token or Personal Access Token (PAT)'
        required: true
    repository-owner:
        description: 'Owner of the repository (user or organisation)'
        required: true
    repository-name:
        description: 'Repository name'
        required: true
    branch-name:
        description: 'The branch to reset on'
        required: true
        default: ''
    commit-sha:
        description: 'Commit SHA to reset to'
        required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    env:
        GITHUB_TOKEN: "${{inputs.github-token}}"
        REPOSITORY_OWNER: "${{inputs.repository-owner}}"
        REPOSITORY_NAME: "${{inputs.repository-name}}"
        BRANCH_NAME: "${{inputs.branch-name}}"
        COMMIT_SHA: "${{inputs.commit-sha}}"
